name: Samsung AP Extractor

on:
  workflow_dispatch:

jobs:
  download-fw:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Free Disk Space (Ubuntu)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip p7zip-full
          python3 -m pip install --upgrade pip
          pip install git+https://github.com/adamwasowicz9-yansk/samloader.git

      - name: Download firmware
        run: |
          # Ten fork samloader automatycznie deszyfruje plik po pobraniu!
          samloader \
            -m SM-S901E \
            -r GLB \
            -i 352497337708509 \
            download \
            -v "S901EXXSDGZB6/S901EOXMDGZB6/S901EXXSDGZB6/S901EXXSDGZB6" \
            -o firmware.zip

      - name: Find firmware zip
        id: firmware
        run: |
          if [ ! -f "firmware.zip" ]; then
            echo "Firmware ZIP not found"
            find . -maxdepth 1 -type f
            exit 1
          fi

          echo "Found: firmware.zip"
          echo "file=firmware.zip" >> "$GITHUB_OUTPUT"

      - name: Extract firmware
        run: |
          mkdir -p firmware
          unzip -o "${{ steps.firmware.outputs.file }}" -d firmware

      - name: Show extracted files
        run: |
          find firmware -type f | sort

      - name: Find AP file
        run: |
          AP_FILE=$(find firmware -type f -name "AP_*.tar.md5" | head -n1)

          if [ -z "$AP_FILE" ]; then
            echo "AP file not found"
            find firmware -type f
            exit 1
          fi

          mkdir -p artifact
          cp "$AP_FILE" artifact/AP.tar.md5

          echo "Selected AP:"
          ls -lh artifact/AP.tar.md5

      - name: Upload AP artifact
        uses: actions/upload-artifact@v4
        with:
          name: AP_S901EXXSDGZB6
          path: artifact/AP.tar.md5
          compression-level: 0
          retention-days: 7
