name: Samsung AP Extractor

on:
  workflow_dispatch:

jobs:
  download-fw:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Free Disk Space (Ubuntu)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full
          python3 -m pip install --upgrade pip
          pip install git+https://github.com/adamwasowicz9-yansk/samloader.git

      - name: Download firmware
        run: |
          samloader \
            -m SM-S901E \
            -r GLB \
            -i 352497337708509 \
            download \
            -v "S901EXXSDGZB6/S901EOXMDGZB6/S901EXXSDGZB6/S901EXXSDGZB6" \
            -o firmware.zip

      - name: Extract ONLY AP File (Save Disk Space)
        run: |
          mkdir -p artifact
          
          # Wyciągamy TYLKO plik AP bezpośrednio do folderu artifact
          7z e firmware.zip -oartifact "AP_*.tar.md5" -r
          
          # Natychmiast usuwamy wielki firmware.zip, aby zwolnić miejsce przed uploadem
          rm -f firmware.zip

          # Zmiana nazwy wyciągniętego pliku wewnątrz folderu artifact
          cd artifact
          mv AP_*.tar.md5 AP.tar.md5
          cd ..

          echo "Selected AP size:"
          ls -lh artifact/AP.tar.md5

      - name: Upload AP artifact
        uses: actions/upload-artifact@v4
        with:
          name: AP_S901EXXSDGZB6
          path: artifact/AP.tar.md5
          compression-level: 0
          retention-days: 7
